export { ErrorPage } from './ErrorPage';
export type { ErrorPageBaseProps, ErrorCode } from './types';

export { default as MinimalistErrorPage } from './minimalist-001';
export { default as DarkErrorPage } from './dark-001';
export { default as GlassmorphismErrorPage } from './glassmorphism-001';
export { default as NeumorphismErrorPage } from './neumorphism-001';
export { default as GradientErrorPage } from './gradient-001';
export { default as BrutalistErrorPage } from './brutalist-001';
export { default as RetroErrorPage } from './retro-001';
export { default as CyberpunkErrorPage } from './cyberpunk-001';
export { default as PastelErrorPage } from './pastel-001';
export { default as CorporateErrorPage } from './corporate-001';
export { default as PlayfulErrorPage } from './playful-001';
export { default as LuxuryErrorPage } from './luxury-001';
export { default as NatureErrorPage } from './nature-001';
export { default as FuturisticErrorPage } from './futuristic-001';
export { default as SketchErrorPage } from './sketch-001';
export { default as MonochromeErrorPage } from './monochrome-001';
export { default as NeonErrorPage } from './neon-001';
export { default as ThreeDErrorPage } from './3d-001';
export { default as FlatErrorPage } from './flat-001';
export { default as MaterialErrorPage } from './material-001';
