import { useState, useMemo, useCallback } from 'react'
import { FilterBar } from './FilterBar'
import { ComponentCard } from './ComponentCard'
import { ComponentPreview } from './ComponentPreview'
import { filterComponents, getAllComponents, getStats } from '../registry'
import type { FilterState, ComponentEntry } from '../types'
import { COMPONENT_CATEGORIES } from '../types'

export function GalleryLayout() {
  const [filters, setFilters] = useState<FilterState>({
    types: [],
    styles: [],
    search: '',
    category: null,
  })
  const [selectedComponent, setSelectedComponent] = useState<ComponentEntry | null>(null)

  // Get all components and stats
  const allComponents = useMemo(() => getAllComponents(), [])
  const stats = useMemo(() => getStats(), [])

  // Filter components
  const filteredComponents = useMemo(() => {
    let results = filterComponents({
      types: filters.types.length > 0 ? filters.types : undefined,
      styles: filters.styles.length > 0 ? filters.styles : undefined,
      search: filters.search || undefined,
    })
    if (filters.category) {
      const categoryTypes = COMPONENT_CATEGORIES[filters.category]
      if (categoryTypes) {
        results = results.filter(c => categoryTypes.includes(c.type))
      }
    }
    return results
  }, [filters])

  const handleFilterChange = useCallback((newFilters: FilterState) => {
    setFilters(newFilters)
  }, [])

  const handleComponentClick = useCallback((entry: ComponentEntry) => {
    setSelectedComponent(entry)
  }, [])

  const handleClosePreview = useCallback(() => {
    setSelectedComponent(null)
  }, [])

  return (
    <div className="min-h-screen bg-[#0f0f0f]">
      {/* Filter Bar */}
      <FilterBar
        filters={filters}
        onFilterChange={handleFilterChange}
        totalCount={allComponents.length}
        filteredCount={filteredComponents.length}
      />

      {/* Main Content */}
      <main className="max-w-[1920px] mx-auto px-4 py-8">
        {/* Empty state */}
        {allComponents.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-32 text-center">
            <div className="w-24 h-24 mb-6 rounded-full bg-white/5 flex items-center justify-center">
              <svg className="w-12 h-12 text-white/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
              </svg>
            </div>
            <h2 className="text-2xl font-semibold text-white mb-2">No components yet</h2>
            <p className="text-white/50 max-w-md mb-8">
              The gallery is empty. Components will appear here as they are generated by AI agents.
            </p>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div className="p-4 bg-white/5 rounded-lg">
                <div className="text-3xl font-bold text-white mb-1">75</div>
                <div className="text-sm text-white/50">Component Types</div>
              </div>
              <div className="p-4 bg-white/5 rounded-lg">
                <div className="text-3xl font-bold text-white mb-1">20</div>
                <div className="text-sm text-white/50">Visual Styles</div>
              </div>
              <div className="p-4 bg-white/5 rounded-lg">
                <div className="text-3xl font-bold text-white mb-1">1,500+</div>
                <div className="text-sm text-white/50">Target Components</div>
              </div>
            </div>
          </div>
        ) : filteredComponents.length === 0 ? (
          // No results state
          <div className="flex flex-col items-center justify-center py-32 text-center">
            <div className="w-24 h-24 mb-6 rounded-full bg-white/5 flex items-center justify-center">
              <svg className="w-12 h-12 text-white/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <h2 className="text-2xl font-semibold text-white mb-2">No matching components</h2>
            <p className="text-white/50">Try adjusting your filters or search query.</p>
          </div>
        ) : (
          // Masonry grid
          <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 2xl:columns-5 gap-4 space-y-4">
            {filteredComponents.map((entry) => (
              <div key={entry.id} className="break-inside-avoid">
                <ComponentCard
                  entry={entry}
                  onClick={() => handleComponentClick(entry)}
                />
              </div>
            ))}
          </div>
        )}

        {/* Stats footer */}
        {allComponents.length > 0 && (
          <div className="mt-16 pt-8 border-t border-white/10">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
              <div>
                <div className="text-3xl font-bold text-white">{stats.total}</div>
                <div className="text-sm text-white/50">Total Components</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-white">{Object.keys(stats.byType).length}</div>
                <div className="text-sm text-white/50">Component Types</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-white">{Object.keys(stats.byStyle).length}</div>
                <div className="text-sm text-white/50">Visual Styles</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-white">
                  {Math.round((stats.total / 1500) * 100)}%
                </div>
                <div className="text-sm text-white/50">Progress to 1500</div>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Component Preview Modal */}
      <ComponentPreview
        entry={selectedComponent}
        onClose={handleClosePreview}
      />
    </div>
  )
}
