import type { ThemeName } from '../_themes';

export interface SearchBoxTheme {
  container: string;
  containerFocused: string;
  input: string;
  icon: string;
  clearButton: string;
  clearButtonHover: string;
  suggestionsContainer: string;
  suggestionItem: string;
  suggestionItemHover: string;
  pageBackground: string;
}

export const searchBoxThemes: Record<ThemeName, SearchBoxTheme> = {
  minimalist: {
    container: 'flex items-center border-b-2 border-gray-200 transition-colors',
    containerFocused: 'border-black',
    input: 'flex-1 bg-transparent text-gray-900 placeholder:text-gray-400 outline-none',
    icon: 'text-gray-400',
    clearButton: 'p-2 text-gray-400 transition-colors',
    clearButtonHover: 'hover:text-black',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border-2 border-black overflow-hidden shadow-lg',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 transition-colors',
    suggestionItemHover: 'hover:bg-gray-100',
    pageBackground: 'bg-white',
  },
  dark: {
    container: 'flex items-center bg-gray-900 rounded-xl border border-gray-800 transition-all',
    containerFocused: 'border-gray-600 ring-2 ring-gray-700',
    input: 'flex-1 bg-transparent text-gray-100 placeholder:text-gray-600 outline-none',
    icon: 'text-gray-500',
    clearButton: 'p-2 rounded-lg text-gray-500 transition-colors',
    clearButtonHover: 'hover:bg-gray-800 hover:text-gray-300',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gray-900 rounded-xl border border-gray-800 shadow-2xl overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-300 transition-colors',
    suggestionItemHover: 'hover:bg-gray-800',
    pageBackground: 'bg-gray-950',
  },
  glassmorphism: {
    container: 'backdrop-blur-xl bg-white/20 rounded-2xl border border-white/30 shadow-2xl flex items-center transition-all',
    containerFocused: 'bg-white/30',
    input: 'flex-1 bg-transparent text-white placeholder:text-white/60 outline-none',
    icon: 'text-white',
    clearButton: 'p-2 rounded-full text-white transition-colors',
    clearButtonHover: 'hover:bg-white/20',
    suggestionsContainer: 'absolute top-full mt-2 w-full backdrop-blur-xl bg-white/20 rounded-2xl shadow-2xl border border-white/30 overflow-hidden',
    suggestionItem: 'w-full px-6 py-3 text-left text-white transition-colors',
    suggestionItemHover: 'hover:bg-white/20',
    pageBackground: 'bg-gradient-to-br from-purple-400 via-pink-500 to-red-500',
  },
  neumorphism: {
    container: 'flex items-center rounded-2xl shadow-[8px_8px_16px_#b8b8b8,-8px_-8px_16px_#ffffff] transition-all',
    containerFocused: 'shadow-[inset_8px_8px_16px_#b8b8b8,inset_-8px_-8px_16px_#ffffff]',
    input: 'flex-1 bg-transparent text-gray-700 placeholder:text-gray-400 outline-none',
    icon: 'text-gray-400',
    clearButton: 'p-2 rounded-full shadow-[4px_4px_8px_#b8b8b8,-4px_-4px_8px_#ffffff] text-gray-500 transition-all',
    clearButtonHover: 'hover:shadow-[inset_4px_4px_8px_#b8b8b8,inset_-4px_-4px_8px_#ffffff]',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gray-200 rounded-2xl shadow-[8px_8px_16px_#b8b8b8,-8px_-8px_16px_#ffffff] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-700 transition-all',
    suggestionItemHover: 'hover:shadow-[inset_4px_4px_8px_#b8b8b8,inset_-4px_-4px_8px_#ffffff]',
    pageBackground: 'bg-gray-200',
  },
  gradient: {
    container: 'flex items-center bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl p-[2px] transition-all',
    containerFocused: 'from-purple-600 to-pink-600',
    input: 'flex-1 bg-white text-gray-900 placeholder:text-gray-400 outline-none rounded-xl',
    icon: 'text-purple-500',
    clearButton: 'p-2 text-purple-500 transition-colors',
    clearButtonHover: 'hover:text-purple-700',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white rounded-xl border border-purple-200 shadow-xl overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 transition-colors',
    suggestionItemHover: 'hover:bg-purple-50',
    pageBackground: 'bg-gradient-to-br from-purple-50 to-pink-50',
  },
  brutalist: {
    container: 'flex items-center bg-white border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transition-all',
    containerFocused: 'shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
    input: 'flex-1 bg-transparent text-black placeholder:text-gray-600 outline-none font-bold',
    icon: 'text-black',
    clearButton: 'p-2 border-2 border-black text-black transition-all',
    clearButtonHover: 'hover:bg-black hover:text-white',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-black font-bold border-b-2 border-black last:border-b-0 transition-colors',
    suggestionItemHover: 'hover:bg-yellow-300',
    pageBackground: 'bg-yellow-400',
  },
  retro: {
    container: 'flex items-center bg-gradient-to-r from-orange-100 to-pink-100 border-2 border-orange-800 rounded-lg shadow-md transition-all',
    containerFocused: 'shadow-lg',
    input: 'flex-1 bg-transparent text-orange-900 placeholder:text-orange-600 outline-none',
    icon: 'text-orange-600',
    clearButton: 'p-2 text-orange-600 transition-colors',
    clearButtonHover: 'hover:text-orange-800',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-orange-100 to-pink-100 border-2 border-orange-800 rounded-lg shadow-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-orange-900 transition-colors',
    suggestionItemHover: 'hover:bg-orange-200',
    pageBackground: 'bg-gradient-to-br from-orange-200 to-pink-200',
  },
  cyberpunk: {
    container: 'flex items-center bg-black border-2 border-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.5)] transition-all',
    containerFocused: 'border-pink-500 shadow-[0_0_20px_rgba(236,72,153,0.5)]',
    input: 'flex-1 bg-transparent text-cyan-400 placeholder:text-cyan-600 outline-none font-mono',
    icon: 'text-cyan-400',
    clearButton: 'p-2 text-cyan-400 transition-all',
    clearButtonHover: 'hover:text-pink-500 hover:shadow-[0_0_10px_rgba(236,72,153,0.5)]',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-black border-2 border-cyan-400 shadow-[0_0_20px_rgba(34,211,238,0.5)] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-cyan-400 font-mono transition-all',
    suggestionItemHover: 'hover:bg-cyan-950 hover:text-pink-500',
    pageBackground: 'bg-black',
  },
  pastel: {
    container: 'flex items-center bg-gradient-to-r from-pink-100 to-purple-100 border border-pink-200 rounded-2xl shadow-sm transition-all',
    containerFocused: 'shadow-md border-purple-300',
    input: 'flex-1 bg-transparent text-purple-900 placeholder:text-purple-400 outline-none',
    icon: 'text-purple-300',
    clearButton: 'p-2 rounded-full text-purple-400 transition-colors',
    clearButtonHover: 'hover:bg-purple-200 hover:text-purple-600',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-pink-100 to-purple-100 border border-purple-200 rounded-2xl shadow-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-purple-900 transition-colors',
    suggestionItemHover: 'hover:bg-purple-200',
    pageBackground: 'bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50',
  },
  corporate: {
    container: 'flex items-center bg-white border border-gray-300 rounded-lg shadow-sm transition-all',
    containerFocused: 'border-blue-500 shadow-md',
    input: 'flex-1 bg-transparent text-gray-900 placeholder:text-gray-500 outline-none',
    icon: 'text-gray-400',
    clearButton: 'p-2 text-gray-400 transition-colors',
    clearButtonHover: 'hover:text-gray-600',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border border-gray-300 rounded-lg shadow-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 transition-colors',
    suggestionItemHover: 'hover:bg-gray-100',
    pageBackground: 'bg-gray-50',
  },
  playful: {
    container: 'flex items-center bg-gradient-to-r from-yellow-200 to-pink-200 border-4 border-purple-500 rounded-3xl shadow-lg transition-all',
    containerFocused: 'border-pink-500 rotate-1',
    input: 'flex-1 bg-transparent text-purple-900 placeholder:text-purple-500 outline-none font-bold',
    icon: 'text-purple-500',
    clearButton: 'p-2 rounded-full bg-purple-500 text-white transition-transform',
    clearButtonHover: 'hover:scale-110 hover:rotate-12',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-yellow-200 to-pink-200 border-4 border-purple-500 rounded-3xl shadow-xl overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-purple-900 font-bold transition-all',
    suggestionItemHover: 'hover:bg-pink-300 hover:translate-x-2',
    pageBackground: 'bg-gradient-to-br from-yellow-100 via-pink-100 to-purple-100',
  },
  '3d': {
    container: 'flex items-center bg-gradient-to-b from-blue-400 to-blue-600 rounded-xl shadow-[0_10px_20px_rgba(0,0,0,0.3),0_6px_6px_rgba(0,0,0,0.23)] transition-all',
    containerFocused: 'shadow-[0_5px_10px_rgba(0,0,0,0.3),0_3px_3px_rgba(0,0,0,0.23)] translate-y-1',
    input: 'flex-1 bg-transparent text-white placeholder:text-blue-200 outline-none',
    icon: 'text-white',
    clearButton: 'p-2 bg-blue-700 rounded-full text-white shadow-md transition-all',
    clearButtonHover: 'hover:shadow-sm hover:translate-y-0.5',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-b from-blue-400 to-blue-600 rounded-xl shadow-[0_10px_20px_rgba(0,0,0,0.3)] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-white transition-all',
    suggestionItemHover: 'hover:bg-blue-700',
    pageBackground: 'bg-gradient-to-br from-blue-100 to-purple-100',
  },
  flat: {
    container: 'flex items-center bg-white border-2 border-gray-200 rounded-lg transition-all',
    containerFocused: 'border-blue-500',
    input: 'flex-1 bg-transparent text-gray-900 placeholder:text-gray-400 outline-none',
    icon: 'text-gray-500',
    clearButton: 'p-2 text-gray-500 transition-colors',
    clearButtonHover: 'hover:text-gray-700',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border-2 border-gray-200 rounded-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 transition-colors',
    suggestionItemHover: 'hover:bg-gray-100',
    pageBackground: 'bg-gray-100',
  },
  futuristic: {
    container: 'flex items-center bg-gradient-to-r from-slate-900 to-slate-800 border border-blue-500/30 rounded-xl shadow-[0_0_15px_rgba(59,130,246,0.3)] transition-all',
    containerFocused: 'shadow-[0_0_25px_rgba(59,130,246,0.5)] border-blue-400/50',
    input: 'flex-1 bg-transparent text-blue-100 placeholder:text-blue-400/50 outline-none font-light tracking-wide',
    icon: 'text-blue-400',
    clearButton: 'p-2 text-blue-400 transition-all',
    clearButtonHover: 'hover:text-blue-300 hover:shadow-[0_0_10px_rgba(59,130,246,0.5)]',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-slate-900 to-slate-800 border border-blue-500/30 rounded-xl shadow-[0_0_20px_rgba(59,130,246,0.4)] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-blue-100 font-light tracking-wide transition-all',
    suggestionItemHover: 'hover:bg-blue-950 hover:text-blue-300',
    pageBackground: 'bg-slate-950',
  },
  luxury: {
    container: 'flex items-center bg-gradient-to-r from-amber-900 to-yellow-900 border border-yellow-600/50 rounded-xl shadow-lg transition-all',
    containerFocused: 'shadow-xl border-yellow-500',
    input: 'flex-1 bg-transparent text-yellow-100 placeholder:text-yellow-600 outline-none',
    icon: 'text-yellow-600',
    clearButton: 'p-2 text-yellow-600 transition-colors',
    clearButtonHover: 'hover:text-yellow-400',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-amber-900 to-yellow-900 border border-yellow-600/50 rounded-xl shadow-xl overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-yellow-100 transition-colors',
    suggestionItemHover: 'hover:bg-yellow-800',
    pageBackground: 'bg-gradient-to-br from-amber-950 to-yellow-950',
  },
  material: {
    container: 'flex items-center bg-white rounded shadow-md transition-all',
    containerFocused: 'shadow-lg',
    input: 'flex-1 bg-transparent text-gray-900 placeholder:text-gray-500 outline-none',
    icon: 'text-gray-600',
    clearButton: 'p-2 rounded-full text-gray-600 transition-all',
    clearButtonHover: 'hover:bg-gray-100',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white rounded shadow-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 transition-colors',
    suggestionItemHover: 'hover:bg-gray-100',
    pageBackground: 'bg-gray-100',
  },
  monochrome: {
    container: 'flex items-center bg-white border-2 border-black transition-all',
    containerFocused: 'border-4',
    input: 'flex-1 bg-transparent text-black placeholder:text-gray-600 outline-none',
    icon: 'text-black',
    clearButton: 'p-2 text-black transition-colors',
    clearButtonHover: 'hover:bg-black hover:text-white',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border-2 border-black overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-black border-b border-gray-300 last:border-b-0 transition-colors',
    suggestionItemHover: 'hover:bg-gray-200',
    pageBackground: 'bg-white',
  },
  nature: {
    container: 'flex items-center bg-gradient-to-r from-green-100 to-emerald-100 border-2 border-green-600 rounded-xl shadow-md transition-all',
    containerFocused: 'shadow-lg border-green-700',
    input: 'flex-1 bg-transparent text-green-900 placeholder:text-green-600 outline-none',
    icon: 'text-green-600',
    clearButton: 'p-2 text-green-600 transition-colors',
    clearButtonHover: 'hover:text-green-800',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-gradient-to-r from-green-100 to-emerald-100 border-2 border-green-600 rounded-xl shadow-lg overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-green-900 transition-colors',
    suggestionItemHover: 'hover:bg-green-200',
    pageBackground: 'bg-gradient-to-br from-green-50 to-emerald-50',
  },
  neon: {
    container: 'flex items-center bg-black border-2 border-pink-500 rounded-lg shadow-[0_0_20px_rgba(236,72,153,0.6)] transition-all',
    containerFocused: 'border-cyan-400 shadow-[0_0_30px_rgba(34,211,238,0.8)]',
    input: 'flex-1 bg-transparent text-pink-400 placeholder:text-pink-600 outline-none',
    icon: 'text-pink-500',
    clearButton: 'p-2 text-pink-500 transition-all',
    clearButtonHover: 'hover:text-cyan-400 hover:shadow-[0_0_10px_rgba(34,211,238,0.8)]',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-black border-2 border-pink-500 rounded-lg shadow-[0_0_30px_rgba(236,72,153,0.6)] overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-pink-400 transition-all',
    suggestionItemHover: 'hover:bg-pink-950 hover:text-cyan-400',
    pageBackground: 'bg-black',
  },
  sketch: {
    container: 'flex items-center bg-white border-2 border-gray-800 rounded-lg shadow-sm transition-all',
    containerFocused: 'shadow-md',
    input: 'flex-1 bg-transparent text-gray-900 placeholder:text-gray-500 outline-none',
    icon: 'text-gray-700',
    clearButton: 'p-2 text-gray-700 transition-colors',
    clearButtonHover: 'hover:text-gray-900',
    suggestionsContainer: 'absolute top-full mt-2 w-full bg-white border-2 border-gray-800 rounded-lg shadow-md overflow-hidden',
    suggestionItem: 'w-full px-4 py-3 text-left text-gray-900 border-b border-gray-300 last:border-b-0 transition-colors',
    suggestionItemHover: 'hover:bg-gray-100',
    pageBackground: 'bg-gray-50',
  },
};

export function getSearchBoxTheme(themeName: ThemeName): SearchBoxTheme {
  const theme = searchBoxThemes[themeName];
  if (!theme) {
    throw new Error(`SearchBox theme "${themeName}" not found`);
  }
  return theme;
}
